{% set name = "pymmcore-widgets" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: aab19523fbaa3a31b63e162ffaf44e844658b43951335f7de8b04d7607e48532


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - fonticon-materialdesignicons6
    - pymmcore
    - pymmcore-plus >=0.11.0
    - python >={{ python_min }}
    - qtpy >=2.0
    - superqt >=0.7.1
    - pint
    - cmap
    - useq-schema >=0.5.0

test:
  imports:
    - pymmcore_widgets
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pymmcore-widgets
  summary: A set of Qt-based widgets onto the pymmcore-plus model
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/pymmcore-plus/pymmcore-widgets

extra:
  recipe-maintainers:
    - goanpeca
    - tlambert03
    - fdrgsp
